#!/bin/bash
# Self-test for attribution.sh: every attribution form it must catch, and the
# ordinary text it must let through. CI runs it before the real check, so a
# pattern that stops matching fails the check instead of passing every PR.
#
#   .github/scripts/attribution.test.sh
set -euo pipefail

CHECK="$(cd "$(dirname "$0")" && pwd)/attribution.sh"
REPO=$(mktemp -d)
trap 'rm -rf "$REPO"' EXIT
git -C "$REPO" init -q
EMPTY_TREE=$(git -C "$REPO" mktree </dev/null)
OWNER_EMAIL=40549302+eshan06@users.noreply.github.com

# commit <parent> <message> [<author name> <author email> [<committer name> <committer email>]]
# Identities default to the owner's; prints the new commit's sha.
commit() {
  GIT_AUTHOR_NAME=${3:-eshans} GIT_AUTHOR_EMAIL=${4:-$OWNER_EMAIL} \
    GIT_COMMITTER_NAME=${5:-eshans} GIT_COMMITTER_EMAIL=${6:-$OWNER_EMAIL} \
    git -C "$REPO" commit-tree "$EMPTY_TREE" -p "$1" -m "$2"
}

BASE=$(GIT_AUTHOR_NAME=eshans GIT_AUTHOR_EMAIL=$OWNER_EMAIL \
  GIT_COMMITTER_NAME=eshans GIT_COMMITTER_EMAIL=$OWNER_EMAIL \
  git -C "$REPO" commit-tree "$EMPTY_TREE" -m base)
failures=0

# expect <clean|attribution|broken> <case> <PR body> [<head> [<base>]]
# Runs the check on base..head (default: no commits) and judges its exit
# status: 0 clean, 1 attribution, anything else broken. A head left empty by
# a failed commit() is kept empty, so the check breaks instead of passing.
expect() {
  local name=$2 body=$3 head=${4-$BASE} base=${5:-$BASE} got=0 out ok
  out=$(cd "$REPO" && PR_BODY="$body" "$CHECK" "$base" "$head" 2>&1) || got=$?
  case $1 in
    clean) ok=$((got == 0)) ;;
    attribution) ok=$((got == 1)) ;;
    broken) ok=$((got > 1)) ;;
  esac
  if [ "$ok" -eq 1 ]; then
    echo "ok     $1: $name"
  else
    echo "WRONG  $name: exit $got, expected $1"
    # Behind "|" so its ::error:: lines stay text, not annotations.
    sed 's/^/       | /' <<<"$out"
    failures=$((failures + 1))
  fi
}

echo "PR descriptions:"
expect attribution 'the create_pull_request footer' \
  $'## What & why\n\nA change.\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01Q9XQMftrEHvjhxbdm89nBz)_'
# \xf0\x9f\xa4\x96 is the robot emoji the footer starts with.
expect attribution 'the Claude Code footer' \
  $'A change.\n\n\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/claude-code)'
expect attribution 'the footer, any link and case' $'A change.\n\n_generated by [claude code](https://claude.ai/code)_'
expect attribution 'a bare session link' $'A change.\n\nhttps://claude.ai/code/session_01SeWFSfciMw9DNTDG2WfsqZ'
expect attribution 'a bare claude.com link' 'Made with https://claude.com/claude-code'
expect attribution 'a co-author line' $'A change.\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>'
expect attribution 'a session trailer' $'A change.\n\nClaude-Session: 01SeWFSfciMw9DNTDG2WfsqZ'
expect attribution 'the footer after a web edit (CRLF)' \
  $'A change.\r\n\r\n---\r\n_Generated by [Claude Code](https://claude.ai/code/session_01Q9)_\r\n'
expect clean 'an empty description' ''
expect clean 'a normal description' "$(
  cat <<'EOF'
## What & why

Strips the Generated by Claude Code footer that create_pull_request appends,
and fails on a `Co-Authored-By:` naming Claude or a `Claude-Session:` trailer.
Design: [Bali student app screens](https://claude.ai/artifact/DdfRPhHu4whXLxe58hBAie)

## Tests

- `/santa-loop`: NICE. Reviewer A (Claude Opus) 0 blockers; Claude Review green.
EOF
)"
expect clean 'a human co-author named Claudette' \
  $'A change.\n\nCo-authored-by: Claudette Smith <claudette@example.com>'

echo "Commits:"
expect clean 'owner-authored, mentions Claude Review' '' \
  "$(commit "$BASE" $'fix(api): a thing\n\nClaude Review asked for it; Claude Opus agreed.')"
expect attribution 'a Co-Authored-By trailer' '' \
  "$(commit "$BASE" $'fix(api): a thing\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>')"
expect attribution 'a Claude-Session trailer' '' \
  "$(commit "$BASE" $'fix(api): a thing\n\nClaude-Session: 01SeWFSfciMw9DNTDG2WfsqZ')"
expect attribution 'the footer in the message' '' \
  "$(commit "$BASE" $'fix(api): a thing\n\nGenerated with [Claude Code](https://claude.ai/code)')"
expect attribution 'author named Claude' '' \
  "$(commit "$BASE" 'fix(api): a thing' Claude claude@example.com)"
expect attribution 'author noreply@anthropic.com' '' \
  "$(commit "$BASE" 'fix(api): a thing' 'Some Name' noreply@anthropic.com)"
expect attribution 'author claude[bot]' '' \
  "$(commit "$BASE" 'fix(api): a thing' 'claude[bot]' '209825114+claude[bot]@users.noreply.github.com')"
expect attribution 'committer Claude' '' \
  "$(commit "$BASE" 'fix(api): a thing' eshans "$OWNER_EMAIL" Claude noreply@anthropic.com)"
BAD=$(commit "$BASE" 'fix(api): a thing' Claude noreply@anthropic.com)
expect attribution 'a bad commit under a clean tip' '' "$(commit "$BAD" 'fix(api): the next thing')"
# Already on the base branch is not this PR's to fix.
expect clean 'a bad commit already on the base' '' "$(commit "$BAD" 'fix(api): the next thing')" "$BAD"

echo "Trouble:"
expect broken 'an unknown base never reads as clean' '' "$BASE" origin/no-such-branch

if [ "$failures" -gt 0 ]; then
  echo "::error::attribution.sh self-test: $failures case(s) wrong — fix the check before trusting it."
  exit 1
fi
echo "attribution.sh self-test: every case behaves."
