import type {
  EventType,
  ParticipationEndedReason,
  ParticipationState,
  PushEnvironment,
  UserRole,
} from '@bali/shared';
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import { newUuidV7 } from './ids.js';

/*
 * The eight tables from docs/ARCHITECTURE.md "Data model", with every rule the
 * database itself enforces. IDs are UUIDv7, generated by the app (a phone must
 * be able to mint one offline), so there is no DB-side default — the
 * `$defaultFn` below covers server-side inserts. Nothing is ever deleted:
 * rows are retired by setting `removed_at`, and every foreign key uses the
 * default NO ACTION so a real DELETE of a referenced row fails loudly.
 */

const id = () => uuid('id').primaryKey().$defaultFn(newUuidV7);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const removedAt = () => timestamp('removed_at', { withTimezone: true });

export const schools = pgTable('schools', {
  id: id(),
  name: text('name').notNull(),
  /**
   * The day the school's data agreement was signed (FERPA's school-official terms, the state's
   * student-privacy law), as the owner records it: a date, which no time zone moves. NULL = none
   * on record, and no teacher invite is minted for the school (T1a).
   */
  agreementSignedAt: date('agreement_signed_at', { mode: 'string' }),
  /**
   * The last day of the school's current school year (or term), as the owner records it (C6b).
   * Past it, the retention run de-identifies the people whose records all lie on or before it.
   * NULL = none on record, and the retention run refuses: it never guesses a year's end.
   */
  schoolYearEndsOn: date('school_year_ends_on', { mode: 'string' }),
  createdAt: createdAt(),
  removedAt: removedAt(),
});

export const users = pgTable('users', {
  id: id(),
  /** Links "who Cognito says this is" to our row (auth decision 2). */
  cognitoId: text('cognito_id').notNull().unique(),
  role: text('role').$type<UserRole>().notNull(),
  /** Nullable: a student exists from their first sign-in, before any school grouping. */
  schoolId: uuid('school_id').references(() => schools.id),
  displayName: text('display_name'),
  createdAt: createdAt(),
  removedAt: removedAt(),
});

export const blocks = pgTable(
  'blocks',
  {
    id: id(),
    /** The ID the physical NFC tag broadcasts. */
    tagId: text('tag_id').notNull(),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // One active owner per physical tag — but a tag can be re-registered
    // after its block row is soft-removed (blocks get reassigned; history stays).
    uniqueIndex('blocks_tag_active_unique')
      .on(t.tagId)
      .where(sql`${t.removedAt} IS NULL`),
  ],
);

export const classes = pgTable(
  'classes',
  {
    id: id(),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    schoolId: uuid('school_id')
      .notNull()
      .references(() => schools.id),
    name: text('name').notNull(),
    /** Students join by typing this (auth decision 3). */
    joinCode: text('join_code').notNull(),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // Codes are short and human-typed: unique among live classes only, so an
    // archived class doesn't reserve its code forever.
    uniqueIndex('classes_join_code_active_unique')
      .on(t.joinCode)
      .where(sql`${t.removedAt} IS NULL`),
    // The teacher's boot call lists their classes on every app launch.
    index('classes_teacher_idx').on(t.teacherId),
  ],
);

export const enrollments = pgTable(
  'enrollments',
  {
    id: id(),
    classId: uuid('class_id')
      .notNull()
      .references(() => classes.id),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // A student is in a class once — but may re-join after a soft removal.
    uniqueIndex('enrollments_active_unique')
      .on(t.classId, t.studentId)
      .where(sql`${t.removedAt} IS NULL`),
    // The student's boot call: "which classes am I in" — every phone, every bell.
    index('enrollments_student_active_idx')
      .on(t.studentId)
      .where(sql`${t.removedAt} IS NULL`),
  ],
);

export const sessions = pgTable(
  'sessions',
  {
    id: id(),
    classId: uuid('class_id')
      .notNull()
      .references(() => classes.id),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    /** When the session is due to end; moved forward by "add time". */
    endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
    /** Set when the session actually ended (teacher or expiry sweep); NULL = running. */
    endedAt: timestamp('ended_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // One class can't have two sessions running ("Rules that keep the data honest").
    uniqueIndex('sessions_one_running_per_class')
      .on(t.classId)
      .where(sql`${t.endedAt} IS NULL`),
    // GET /v1/classes/{id}/reports/sessions (R3) — a class's sessions, newest
    // first, a page at a time (`classSessions`), so a page costs its own size
    // however many sessions the class has run.
    index('sessions_class_started_idx').on(t.classId, t.startedAt, t.id),
  ],
);

export const participations = pgTable(
  'participations',
  {
    id: id(),
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    /** The current picture; overwritten as the student's state changes (decision 1). */
    state: text('state').$type<ParticipationState>().notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull(),
    /** Overwritten by the ~30s check-in; never produces an events row (decision 7). */
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    /**
     * When a silence episode opened for this participation — a focused phone that
     * stopped checking in past SILENCE_THRESHOLD_MS; NULL = in contact. The sweep
     * sets it (emitting one `went_silent`), a check-in clears it (emitting one
     * `came_back`), so each episode's two events fire exactly once. This is the
     * episode marker for the event feed; the `silent` shown on a grid is still
     * derived from `last_seen_at` on read (decision 7), never from this column.
     */
    silentSince: timestamp('silent_since', { withTimezone: true }),
    /** Set when the participation ended; NULL = live. */
    endedAt: timestamp('ended_at', { withTimezone: true }),
    /** Why it ended — typed, so reports can never miscount a switch as an unlock (decision 4). */
    endedReason: text('ended_reason').$type<ParticipationEndedReason>(),
    createdAt: createdAt(),
  },
  (t) => [
    // One row per student per session; the row is updated, not duplicated.
    uniqueIndex('participations_session_student_unique').on(t.sessionId, t.studentId),
    // A student can be in only one session at a time (decision 4).
    uniqueIndex('participations_one_live_per_student')
      .on(t.studentId)
      .where(sql`${t.endedAt} IS NULL`),
    // GET /v1/me/history — the classes that ended with the student in them,
    // newest first: the "class ended" moments, which the session's own event
    // records without the student's id.
    index('participations_student_ended_idx').on(t.studentId, t.endedAt),
    // ended_at and ended_reason move together: a live row has neither, an ended
    // row has both. Reports branch on ended_reason, so an ended-but-reasonless
    // row (or the reverse) would be a silent miscount — the DB refuses it.
    check(
      'participations_ended_consistent',
      sql`(${t.endedAt} IS NULL) = (${t.endedReason} IS NULL)`,
    ),
  ],
);

export const events = pgTable(
  'events',
  {
    id: id(),
    /**
     * The stream number live screens resume from (rule 6). Handed out when the
     * write starts, so consumers re-read with an overlap window on reconnect.
     */
    seq: bigint('seq', { mode: 'number' }).generatedAlwaysAsIdentity(),
    /**
     * Idempotency key, minted by whichever device caused the event. The unique
     * constraint IS the dedupe: if the same tap arrives twice, one insert wins
     * and the other is refused — our code never has to win a race.
     */
    eventId: uuid('event_id').notNull().unique(),
    type: text('type').$type<EventType>().notNull(),
    /** Nullable: enrollment events happen outside any session. */
    sessionId: uuid('session_id').references(() => sessions.id),
    classId: uuid('class_id').references(() => classes.id),
    /** The user this event is about (the tapping student, the unlocking student…). */
    userId: uuid('user_id').references(() => users.id),
    payload: jsonb('payload'),
    /** When it happened on the device — already clamped to the session window (rule 1). */
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * The order the phone acted in (A12): its outbox file's id and the record's place in it, a
     * counter no clock moves — what orders a student's own unlock against their return. Both or
     * neither; neither on an event no phone numbered (an old build's, one the server mints). A
     * tap converted at Start carries its armed row's. Columns, not payload, so the live feed
     * never carries them.
     */
    orderInstall: uuid('order_install'),
    orderSeq: bigint('order_seq', { mode: 'number' }),
  },
  (t) => [
    // The catch-up read: "everything for this session after seq N".
    index('events_session_seq_idx').on(t.sessionId, t.seq),
    // GET /v1/me/history — the student's own moments, newest first, read in
    // `occurred_at` order a page at a time (`getHistoryPage`). NEITHER column
    // orders that timeline on its own. It is the one read that crosses
    // sessions, and a switch gives the `tap_in` a LOWER `seq` than the
    // `left_for_other_session` it causes (the event is minted first, so a
    // skipped tap never ends a participation) — by `seq` the student joins
    // period 2 before leaving period 1 — while the engine stamps ONE
    // `occurred_at` on the pair, so they tie. So the read orders by
    // `occurred_at`, then a leave before anything else at the same instant,
    // then `seq`; this index serves the first key and the sort takes the tie.
    // It replaced `events_user_seq_idx` (user_id, seq), which no read used.
    index('events_user_occurred_idx').on(t.userId, t.occurredAt),
    // GET /v1/classes/{id}/reports/… — a class's events over a date range.
    index('events_class_occurred_idx').on(t.classId, t.occurredAt),
    // POST /v1/taps — every tap looks up the unlocks sent under it before it
    // arrived, which its landing files (decision 11, `unlocksAwaitingTap`).
    // Partial, holding only unlocks kept with no session, so that is one probe.
    index('events_unattached_tap_idx')
      .on(sql`(${t.payload}->>'claimed_tap_event_id')`)
      .where(sql`${t.type} = 'unlock' and ${t.sessionId} is null`),
    // POST /v1/taps and a Start — a tap is late when the phone made a tap of the
    // student's after it, from the same install, landed in another session (A14,
    // `tapsMadeSince`): the install's taps past a seq, which no other index can
    // bound, since that order is the phone's and not the clock's.
    index('events_order_tap_idx')
      .on(t.orderInstall, t.orderSeq)
      .where(sql`${t.type} = 'tap_in'`),
    // An unlock's reason now is its latest change's (A20, `changedReasons`), read
    // by the unlock's id. Partial, holding only the changes, so each is a probe.
    index('events_unlock_reason_idx')
      .on(sql`(${t.payload}->>'unlock_event_id')`)
      .where(sql`${t.type} = 'unlock_reason_changed'`),
    // An order is its install and its seq together: half of one orders nothing.
    check('events_order_whole', sql`(${t.orderInstall} IS NULL) = (${t.orderSeq} IS NULL)`),
  ],
);

/*
 * Armed taps (data-model decision 5). A tap before the teacher has started has
 * no session yet, so it can't be a participation. It is saved as student +
 * teacher (one block serves all of a teacher's classes; the class is only known
 * once a session starts), waits, and becomes a participation when the teacher
 * presses Start. It expires at the end of the school day. This is the ninth
 * table the tap-flow section always implied; the data-model list is updated to
 * match.
 */
export const armedTaps = pgTable(
  'armed_taps',
  {
    id: id(),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    /** Which physical block was tapped — for auditing; the class isn't known yet. */
    blockId: uuid('block_id').references(() => blocks.id),
    /**
     * The client's idempotency key. It becomes the tap_in event's id when this
     * armed tap converts to a participation, so a retry that arrives after the
     * session started dedupes against the same key (rule 4).
     */
    eventId: uuid('event_id').notNull().unique(),
    /** Device time of the tap; clamped into the session window at conversion (rule 1). */
    deviceTime: timestamp('device_time', { withTimezone: true }).notNull(),
    /** The phone's own order for the tap (A12), kept for the `tap_in` its conversion records. */
    orderInstall: uuid('order_install'),
    orderSeq: bigint('order_seq', { mode: 'number' }),
    /** End of the school day; conversion skips a past-expiry tap, a sweep clears it. */
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /**
     * Set at the session start that took this tap: it became a participation,
     * or was declined because its tap had already landed (decision 5,
     * recorded as `armed_tap_skipped`) or a later tap went ahead of it (A14,
     * its `tap_in` noted `superseded`). Set as it lands for a tap already late
     * then (A14): it never waits. Set by the student's account deletion (C3)
     * for a tap still waiting. NULL = still waiting.
     */
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // At most one waiting tap per student per teacher — a re-tap before Start
    // doesn't pile up (decision 5: "nobody taps twice").
    uniqueIndex('armed_taps_student_teacher_waiting_unique')
      .on(t.studentId, t.teacherId)
      .where(sql`${t.consumedAt} IS NULL`),
    // Conversion at Start looks up a teacher's waiting taps.
    index('armed_taps_teacher_waiting_idx')
      .on(t.teacherId)
      .where(sql`${t.consumedAt} IS NULL`),
    check('armed_taps_order_whole', sql`(${t.orderInstall} IS NULL) = (${t.orderSeq} IS NULL)`),
  ],
);

/*
 * Teacher invites (Phase 4, T1a). The owner mints one for a school whose data agreement is signed
 * (`npm run school -- invite`) and gives its code to one teacher; redeeming it (T1b) makes that
 * account a teacher at the school. The code itself is never stored: it is shown once, at minting,
 * and only its hash is kept, so a copy of this table opens no school.
 */
export const teacherInvites = pgTable(
  'teacher_invites',
  {
    id: id(),
    schoolId: uuid('school_id')
      .notNull()
      .references(() => schools.id),
    /** SHA-256 of the code, in hex (`hashInviteCode`). Unique: one invite per code. */
    codeHash: text('code_hash').notNull().unique(),
    createdAt: createdAt(),
    /** 14 days after `created_at`, on the database's clock (the owner's ruling, 2026-10-04). */
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /**
     * The redeem (T1b): when, by whom, and the request's `eventId` — all three or none. Single
     * use: a redeem is one UPDATE guarded by `redeemed_at IS NULL`, so of two at once only one
     * sets them, and a replay finds its own by the unique `redeem_event_id`. Once set, the row
     * never changes again: the database refuses it (0013_teacher_invites_single_use.sql).
     */
    redeemedAt: timestamp('redeemed_at', { withTimezone: true }),
    redeemedBy: uuid('redeemed_by').references(() => users.id),
    redeemEventId: uuid('redeem_event_id').unique(),
  },
  (t) => [
    // Only a hash fits: 64 lower-case hex digits, which no code (upper-case symbols) can be.
    check('teacher_invites_code_hash_hex', sql`${t.codeHash} ~ '^[0-9a-f]{64}$'`),
    // A redeem is whole: its time, its teacher and its eventId together, or none of them.
    check(
      'teacher_invites_redeem_whole',
      sql`(${t.redeemedAt} IS NULL) = (${t.redeemedBy} IS NULL) AND (${t.redeemedAt} IS NULL) = (${t.redeemEventId} IS NULL)`,
    ),
  ],
);

/*
 * Device tokens (N3; ARCHITECTURE, "Push: a doorbell for students"): a student's phone's APNs
 * token, so a Start can ring the students it converts (N5). Keyed by the token, so one phone has
 * one current owner: registered from another account, the row moves to it. Written beside the
 * transition engine (`device-tokens.ts`), never inside it. Personal data, and the one table whose
 * rows are really deleted: a removed or gone token is no record of anything, and nothing
 * references it.
 */
export const deviceTokens = pgTable(
  'device_tokens',
  {
    /** The token APNs gave the phone, in lower-case hex. */
    token: text('token').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    environment: text('environment').$type<PushEnvironment>().notNull(),
    /** The eventId of the register that wrote the row as it is: a replay finds its own here. */
    eventId: uuid('event_id').notNull().unique(),
    createdAt: createdAt(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // A Start reads a student's tokens (N5); a deletion removes them (N4).
    index('device_tokens_user_idx').on(t.userId),
    check('device_tokens_token_hex', sql`${t.token} ~ '^[0-9a-f]{64,200}$'`),
    check('device_tokens_environment', sql`${t.environment} IN ('sandbox', 'production')`),
  ],
);

/*
 * The 13+ check's yes (C7-server; ARCHITECTURE, Auth, "Under 13"): one row per account that
 * confirmed it is 13 or older, never a birth date or an age, and none for an answer under 13, which
 * the phone never sends. Written beside the transition engine (`age-checks.ts`). Never unset: only
 * the account's deletion (C3), a school's disposal (C6a) or the retention run (C6b) deletes it.
 */
export const ageChecks = pgTable('age_checks', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id),
  /** The eventId of the request that recorded it: a replay finds its own here. */
  eventId: uuid('event_id').notNull().unique(),
  /** When the server recorded it, by its own clock. */
  createdAt: createdAt(),
});

/*
 * A deleted account's Cognito sign-in, waiting for the API to delete it from the pool (the owner's
 * decision, 2026-10-09): queued by `deleteAccount` in its own transaction, or by `DELETE /v1/me` for
 * a sign-in with no account here, and written beside the engine (`cognito-deletions.ts`). Keyed to
 * the Cognito user, not to a `users` row, since a sign-in the server never saw is queued too; really
 * deleted once its sign-in is gone. Its three ids are personal data: never logged, not exported (C5).
 */
export const cognitoDeletions = pgTable(
  'cognito_deletions',
  {
    id: id(),
    /** The access token's `iss`: the pool. Only rows of this deploy's `AUTH_ISSUER` are tried. */
    issuer: text('issuer').notNull(),
    /** The access token's `username`: the name AdminGetUser and AdminDeleteUser take. */
    username: text('username').notNull(),
    /** The access token's `sub`: the user is deleted only while `username` still names it. */
    sub: text('sub').notNull(),
    /** Tries claimed so far. */
    attempts: integer('attempts').notNull().default(0),
    /** When it may be tried next: when queued, then later after each claim (a backoff). */
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull(),
    createdAt: createdAt(),
  },
  // One per sign-in: a deletion's retry queues nothing more.
  (t) => [uniqueIndex('cognito_deletions_sign_in_unique').on(t.issuer, t.sub)],
);

/*
 * A live lesson's questions and answers (Phase 7; ARCHITECTURE, "Live lesson", decision 4), written
 * only by the transition engine. A question is asked within a running session; a response is a
 * student's answer now, and never an event, so the stream never names who answered what.
 */
export const questions = pgTable(
  'questions',
  {
    id: id(),
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id),
    prompt: text('prompt').notNull(),
    /** The options' texts, 2–6; an answer names one by its index. */
    options: jsonb('options').$type<string[]>().notNull(),
    /** The correct option's index, when the teacher gave one. */
    correctOption: integer('correct_option'),
    /** The open's idempotency key, and its `question_opened` event's id. */
    eventId: uuid('event_id').notNull().unique(),
    openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
    /** NULL = open. */
    closedAt: timestamp('closed_at', { withTimezone: true }),
    /** Whether its close showed the correct option. */
    revealed: boolean('revealed').notNull().default(false),
    /** The teacher who opened it. */
    createdBy: uuid('created_by')
      .notNull()
      .references(() => users.id),
  },
  (t) => [
    // One open question per session: the backstop under the open's lock on the session.
    uniqueIndex('questions_one_open_per_session')
      .on(t.sessionId)
      .where(sql`${t.closedAt} IS NULL`),
  ],
);

export const responses = pgTable(
  'responses',
  {
    id: id(),
    questionId: uuid('question_id')
      .notNull()
      .references(() => questions.id),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    /** The index of the option chosen. */
    option: integer('option').notNull(),
    /** The answer now's idempotency key: a replaced answer's is not kept. */
    eventId: uuid('event_id').notNull().unique(),
    /** When the server received the answer now, by its own clock. */
    answeredAt: timestamp('answered_at', { withTimezone: true }).notNull(),
  },
  // One answer per student per question, replaced while the question is open.
  (t) => [uniqueIndex('responses_question_student_unique').on(t.questionId, t.studentId)],
);
