import type {
  EventType,
  ParticipationEndedReason,
  ParticipationState,
  UserRole,
} from '@bali/shared';
import { sql } from 'drizzle-orm';
import {
  bigint,
  check,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import { newUuidV7 } from './ids.js';

/*
 * The eight tables from docs/ARCHITECTURE.md "Data model", with every rule the
 * database itself enforces. IDs are UUIDv7, generated by the app (a phone must
 * be able to mint one offline), so there is no DB-side default — the
 * `$defaultFn` below covers server-side inserts. Nothing is ever deleted:
 * rows are retired by setting `removed_at`, and every foreign key uses the
 * default NO ACTION so a real DELETE of a referenced row fails loudly.
 */

const id = () => uuid('id').primaryKey().$defaultFn(newUuidV7);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const removedAt = () => timestamp('removed_at', { withTimezone: true });

export const schools = pgTable('schools', {
  id: id(),
  name: text('name').notNull(),
  createdAt: createdAt(),
  removedAt: removedAt(),
});

export const users = pgTable('users', {
  id: id(),
  /** Links "who Cognito says this is" to our row (auth decision 2). */
  cognitoId: text('cognito_id').notNull().unique(),
  role: text('role').$type<UserRole>().notNull(),
  /** Nullable: a student exists from their first sign-in, before any school grouping. */
  schoolId: uuid('school_id').references(() => schools.id),
  displayName: text('display_name'),
  createdAt: createdAt(),
  removedAt: removedAt(),
});

export const blocks = pgTable(
  'blocks',
  {
    id: id(),
    /** The ID the physical NFC tag broadcasts. */
    tagId: text('tag_id').notNull(),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // One active owner per physical tag — but a tag can be re-registered
    // after its block row is soft-removed (blocks get reassigned; history stays).
    uniqueIndex('blocks_tag_active_unique')
      .on(t.tagId)
      .where(sql`${t.removedAt} IS NULL`),
  ],
);

export const classes = pgTable(
  'classes',
  {
    id: id(),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    schoolId: uuid('school_id')
      .notNull()
      .references(() => schools.id),
    name: text('name').notNull(),
    /** Students join by typing this (auth decision 3). */
    joinCode: text('join_code').notNull(),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // Codes are short and human-typed: unique among live classes only, so an
    // archived class doesn't reserve its code forever.
    uniqueIndex('classes_join_code_active_unique')
      .on(t.joinCode)
      .where(sql`${t.removedAt} IS NULL`),
    // The teacher's boot call lists their classes on every app launch.
    index('classes_teacher_idx').on(t.teacherId),
  ],
);

export const enrollments = pgTable(
  'enrollments',
  {
    id: id(),
    classId: uuid('class_id')
      .notNull()
      .references(() => classes.id),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    createdAt: createdAt(),
    removedAt: removedAt(),
  },
  (t) => [
    // A student is in a class once — but may re-join after a soft removal.
    uniqueIndex('enrollments_active_unique')
      .on(t.classId, t.studentId)
      .where(sql`${t.removedAt} IS NULL`),
    // The student's boot call: "which classes am I in" — every phone, every bell.
    index('enrollments_student_active_idx')
      .on(t.studentId)
      .where(sql`${t.removedAt} IS NULL`),
  ],
);

export const sessions = pgTable(
  'sessions',
  {
    id: id(),
    classId: uuid('class_id')
      .notNull()
      .references(() => classes.id),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    /** When the session is due to end; moved forward by "add time". */
    endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
    /** Set when the session actually ended (teacher or expiry sweep); NULL = running. */
    endedAt: timestamp('ended_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // One class can't have two sessions running ("Rules that keep the data honest").
    uniqueIndex('sessions_one_running_per_class')
      .on(t.classId)
      .where(sql`${t.endedAt} IS NULL`),
  ],
);

export const participations = pgTable(
  'participations',
  {
    id: id(),
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    /** The current picture; overwritten as the student's state changes (decision 1). */
    state: text('state').$type<ParticipationState>().notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull(),
    /** Overwritten by the ~30s check-in; never produces an events row (decision 7). */
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    /**
     * When a silence episode opened for this participation — a focused phone that
     * stopped checking in past SILENCE_THRESHOLD_MS; NULL = in contact. The sweep
     * sets it (emitting one `went_silent`), a check-in clears it (emitting one
     * `came_back`), so each episode's two events fire exactly once. This is the
     * episode marker for the event feed; the `silent` shown on a grid is still
     * derived from `last_seen_at` on read (decision 7), never from this column.
     */
    silentSince: timestamp('silent_since', { withTimezone: true }),
    /** Set when the participation ended; NULL = live. */
    endedAt: timestamp('ended_at', { withTimezone: true }),
    /** Why it ended — typed, so reports can never miscount a switch as an unlock (decision 4). */
    endedReason: text('ended_reason').$type<ParticipationEndedReason>(),
    createdAt: createdAt(),
  },
  (t) => [
    // One row per student per session; the row is updated, not duplicated.
    uniqueIndex('participations_session_student_unique').on(t.sessionId, t.studentId),
    // A student can be in only one session at a time (decision 4).
    uniqueIndex('participations_one_live_per_student')
      .on(t.studentId)
      .where(sql`${t.endedAt} IS NULL`),
    // GET /v1/me/history — the classes that ended with the student in them,
    // newest first: the "class ended" moments, which the session's own event
    // records without the student's id.
    index('participations_student_ended_idx').on(t.studentId, t.endedAt),
    // ended_at and ended_reason move together: a live row has neither, an ended
    // row has both. Reports branch on ended_reason, so an ended-but-reasonless
    // row (or the reverse) would be a silent miscount — the DB refuses it.
    check(
      'participations_ended_consistent',
      sql`(${t.endedAt} IS NULL) = (${t.endedReason} IS NULL)`,
    ),
  ],
);

export const events = pgTable(
  'events',
  {
    id: id(),
    /**
     * The stream number live screens resume from (rule 6). Handed out when the
     * write starts, so consumers re-read with an overlap window on reconnect.
     */
    seq: bigint('seq', { mode: 'number' }).generatedAlwaysAsIdentity(),
    /**
     * Idempotency key, minted by whichever device caused the event. The unique
     * constraint IS the dedupe: if the same tap arrives twice, one insert wins
     * and the other is refused — our code never has to win a race.
     */
    eventId: uuid('event_id').notNull().unique(),
    type: text('type').$type<EventType>().notNull(),
    /** Nullable: enrollment events happen outside any session. */
    sessionId: uuid('session_id').references(() => sessions.id),
    classId: uuid('class_id').references(() => classes.id),
    /** The user this event is about (the tapping student, the unlocking student…). */
    userId: uuid('user_id').references(() => users.id),
    payload: jsonb('payload'),
    /** When it happened on the device — already clamped to the session window (rule 1). */
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The catch-up read: "everything for this session after seq N".
    index('events_session_seq_idx').on(t.sessionId, t.seq),
    // GET /v1/me/history — the student's own moments, newest first, read in
    // `occurred_at` order a page at a time (`getHistoryPage`). NEITHER column
    // orders that timeline on its own. It is the one read that crosses
    // sessions, and a switch gives the `tap_in` a LOWER `seq` than the
    // `left_for_other_session` it causes (the event is minted first, so a
    // skipped tap never ends a participation) — by `seq` the student joins
    // period 2 before leaving period 1 — while the engine stamps ONE
    // `occurred_at` on the pair, so they tie. So the read orders by
    // `occurred_at`, then a leave before anything else at the same instant,
    // then `seq`; this index serves the first key and the sort takes the tie.
    // It replaced `events_user_seq_idx` (user_id, seq), which no read used.
    index('events_user_occurred_idx').on(t.userId, t.occurredAt),
    // GET /v1/classes/{id}/reports/… — a class's events over a date range.
    index('events_class_occurred_idx').on(t.classId, t.occurredAt),
    // POST /v1/taps — every tap looks up the unlocks sent under it before it
    // arrived, which its landing files (decision 11, `unlocksAwaitingTap`).
    // Partial, holding only unlocks kept with no session, so that is one probe.
    index('events_unattached_tap_idx')
      .on(sql`(${t.payload}->>'claimed_tap_event_id')`)
      .where(sql`${t.type} = 'unlock' and ${t.sessionId} is null`),
  ],
);

/*
 * Armed taps (data-model decision 5). A tap before the teacher has started has
 * no session yet, so it can't be a participation. It is saved as student +
 * teacher (one block serves all of a teacher's classes; the class is only known
 * once a session starts), waits, and becomes a participation when the teacher
 * presses Start. It expires at the end of the school day. This is the ninth
 * table the tap-flow section always implied; the data-model list is updated to
 * match.
 */
export const armedTaps = pgTable(
  'armed_taps',
  {
    id: id(),
    studentId: uuid('student_id')
      .notNull()
      .references(() => users.id),
    teacherId: uuid('teacher_id')
      .notNull()
      .references(() => users.id),
    /** Which physical block was tapped — for auditing; the class isn't known yet. */
    blockId: uuid('block_id').references(() => blocks.id),
    /**
     * The client's idempotency key. It becomes the tap_in event's id when this
     * armed tap converts to a participation, so a retry that arrives after the
     * session started dedupes against the same key (rule 4).
     */
    eventId: uuid('event_id').notNull().unique(),
    /** Device time of the tap; clamped into the session window at conversion (rule 1). */
    deviceTime: timestamp('device_time', { withTimezone: true }).notNull(),
    /** End of the school day; conversion skips a past-expiry tap, a sweep clears it. */
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /**
     * Set at the session start that took this tap: it became a participation,
     * or was declined because its tap had already landed (decision 5,
     * recorded as `armed_tap_skipped`). NULL = still waiting.
     */
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // At most one waiting tap per student per teacher — a re-tap before Start
    // doesn't pile up (decision 5: "nobody taps twice").
    uniqueIndex('armed_taps_student_teacher_waiting_unique')
      .on(t.studentId, t.teacherId)
      .where(sql`${t.consumedAt} IS NULL`),
    // Conversion at Start looks up a teacher's waiting taps.
    index('armed_taps_teacher_waiting_idx')
      .on(t.teacherId)
      .where(sql`${t.consumedAt} IS NULL`),
  ],
);
